name: Build and test
run-name: Build and test 🔨by ${{ github.actor }}
on:
  push:
    branches:
      - '**'        # matches every branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build and Test with Gradle
        run: ./gradlew build --no-daemon